version: "3"

services:
  postgres:
    image: "postgres:11"
    environment:
      - "POSTGRES_USER=graphqltypeorm"
      - "POSTGRES_DB=graphql_typeorm_soft_delete"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    expose:
      - "5432"
    ports:
      - "5440:5432"
