version: "3"

services:
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=graphqlsequelize"
      - "POSTGRES_DB=graphql_sequelize"
    expose:
      - "5432"
    ports:
      - "5437:5432"
