version: "3"

services:
  postgres:
    image: "postgres:11"
    environment:
      - "POSTGRES_USER=graphqlsequelize"
      - "POSTGRES_DB=graphql_sequelize"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    expose:
      - "5432"
    ports:
      - "5441:5432"
